raise the MSRV to 1.88 (#1694)
dropshot_endpoint already uses a let chain (stabilized in Rust 1.88), so
the declared MSRV of 1.85 no longer builds:

    error[E0658]: `let` expressions in this position are unstable
       --> dropshot_endpoint/src/api_trait.rs:235:20

Specify an MSRV of 1.88 and fix CI to check for it. In upcoming commits
we're going to add more let chains.

After #1695 and this PR, the CI test matrix is:

* all tests except trybuild ones on MSRV and stable, and across
Linux/macOS/Windows
* trybuild tests on pinned toolchain on Linux